version: 2
jobs:
  build:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run:
        command: echo "Mama we made it!"
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:12
#     steps:
#       - checkout
#       - run: echo \"Mama we made it!\"