version: 2.1
commands:
  sayhello:
    description: 'What up'
    parameters:
      to:
        type: string
        default: 'Whats Good'
    steps:
      - run: |
          echo << parameters.to >>
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - sayhello:
          to: 'Mike'

  ihavecode:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code here
          command: |
            ls -al
  runwithnode:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Running in Node
          command: |
            node -v

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Hello-World
      - ihavecode:
          requires:
            - Hello-World
      - runwithnode:
          requires:
            - Hello-World
