version: 2.1
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeine'
  ihavecode:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code here
          command: |
            ls -al
    runwithnode:
      docker:
        - image: circleci/node:10-browsers
      steps:
        - run:
            name: Running in Node
            command: |
              node -v

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Hello-World
      - ihavecode:
          requires:
            - Hello-World
      - runwithnode:
          requires:
            - Hello-World
